-- Create a list of books to feature in an exhibit.

-- Make a pick list of books published from 1890-1899 
-- which are not currently checked out.


SELECT TITLE, PUBLISHED, RETURNEDDATE
FROM BOOKS 
JOIN LOANS 
ON BOOKS.BOOKID=LOANS.LOANID
WHERE PUBLISHED BETWEEN 1890 AND 1900
  AND  LOANS.RETURNEDDATE IS NOT NULL
--BETTER WAY TO DO IT IS BELOW, ABOVE DOESNT ACCOUNT FOR CHECKEDOUT BOOKS WELL 

SELECT TITLE, BARCODE 
FROM BOOKS 
WHERE PUBLISHED BETWEEN 1890 AND 1899 
AND (BOOKID NOT IN (
                      SELECT BOOKID 
                      FROM LOANS 
                      WHERE RETURNEDDATE IS NULL))
ORDER BY TITLE

