-- Create two reports about book statistics.

-- Report 1: Show how many titles were published 
-- in each year.

-- Report 2: Show the five books that have been
-- checked out the most.

SELECT PUBLISHED, COUNT(DISTINCT(TITLE)) AS NUMBEREACHYEAR --NEEDS A DISTINCT AS THE SAME BOOK CANNOT COUNT
FROM BOOKS 
GROUP BY PUBLISHED
ORDER BY NUMBEREACHYEAR DESC

SELECT BOOKS.TITLE, BOOKS.BOOKID, COUNT(BOOKS.TITLE) AS NUMBEROFTIMESCHECKEDOUT 
FROM LOANS 
JOIN BOOKS 
ON BOOKS.BOOKID=LOANS.BOOKID
GROUP BY BOOKS.TITLE
ORDER BY NUMBEROFTIMESCHECKEDOUT DESC
LIMIT 5
--USE TITLE SO THAT THE SAME BOOK WITH DIFFERENT ID DOESNT APPEAR TWICE 
